storage: bucket replication support (#668)
# Description
<!--
* Prefix: the title with the component name being changed. Add a short
and self describing sentence to ease the review
* Please add a few lines providing context and describing the change
* Please self comment changes whenever applicable to help with the
review process
* Please keep the checklist as part of the PR. Tick what applies to this
change.
-->

Adds support for updating bucket replication in the CLI, with syntax
[similar to
`aws-cli`'s](https://docs.aws.amazon.com/cli/latest/reference/s3api/put-bucket-replication.html#options)

Also displays replication status when available when showing the details
of an object in SOS
## Checklist
(For exoscale contributors)

* [x] Changelog updated (under *Unreleased* block)
* [x] Testing

## Testing

<!--
Describe the tests you did
-->

```
➜  ~/exo/cli git:(tgrondier/sc-118859/exo-cli-bucket-replication-support) go run . storage bucket replication show sos://box -z ch-dk-2                                                                                                                                                                     25-02-20 14:39 
error: operation error S3: GetBucketReplication, https response error StatusCode: 404, RequestID: 6d52c74f-298f-4e09-b18d-3e826c9bd03c, HostID: 6d52c74f-298f-4e09-b18d-3e826c9bd03c, api error ReplicationConfigurationNotFoundError: The replication configuration was not found.
exit status 1

➜  ~/exo/cli git:(tgrondier/sc-118859/exo-cli-bucket-replication-support) go run . storage bucket replication put sos://box file://../replication.json  -z ch-dk-2                                                                                                                                          25-02-20 14:39 
➜  ~/exo/cli git:(tgrondier/sc-118859/exo-cli-bucket-replication-support) go run . storage bucket replication show sos://box -z ch-dk-2                                                                                                                                                                     25-02-20 14:39 
┼────────────────────┼───────────────────────────────────────────────┼
│ BUCKET REPLICATION │                                               │
┼────────────────────┼───────────────────────────────────────────────┼
│ Bucket             │ box                                           │
│ Role               │ c5d6718d-16c1-426f-8b8c-a9ffd5b7370b          │
│ Rules              │                                               │
│                    │   ID                        foo               │
│                    │   Status                    Enabled           │
│                    │   Priority                                1   │
│                    │   DeleteMarkerReplication   Disabled          │
│                    │   Filter prefix                               │
│                    │   Destination Bucket        box-replication   │
│                    │                                               │
┼────────────────────┼───────────────────────────────────────────────┼
➜  ~/exo/cli git:(tgrondier/sc-118859/exo-cli-bucket-replication-support) go run . storage bucket replication show sos://box -z ch-dk-2 -O json | jq                                                                                                                                                        25-02-20 14:39 
{
  "Role": "c5d6718d-16c1-426f-8b8c-a9ffd5b7370b",
  "Rules": [
    {
      "Destination": {
        "Bucket": "box-replication",
        "AccessControlTranslation": null,
        "Account": null,
        "EncryptionConfiguration": null,
        "Metrics": null,
        "ReplicationTime": null,
        "StorageClass": ""
      },
      "Status": "Enabled",
      "DeleteMarkerReplication": {
        "Status": "Disabled"
      },
      "ExistingObjectReplication": null,
      "Filter": {
        "Prefix": ""
      },
      "ID": "foo",
      "Priority": 1,
      "SourceSelectionCriteria": null
    }
  ],
  "Bucket": "box"
}
➜  ~/exo/cli git:(tgrondier/sc-118859/exo-cli-bucket-replication-support) go run . storage ls box                                                                                                                                                                                                           25-02-20 14:40 
2025-02-20 10:26:33 UTC 54 KiB  Screenshot_20231127_112615.png
➜  ~/exo/cli git:(tgrondier/sc-118859/exo-cli-bucket-replication-support) go run . storage show sos://box/Screenshot_20231127_112615.png                                                                                                                                                                    25-02-20 14:40 
┼────────────────────┼───────────────────────────────────────────────────────────────┼
│      STORAGE       │                                                               │
┼────────────────────┼───────────────────────────────────────────────────────────────┼
│ Path               │ Screenshot_20231127_112615.png                                │
│ Bucket             │ box                                                           │
...
│ Replication Status │ COMPLETED                                                     │

┼────────────────────┼───────────────────────────────────────────────────────────────┼
➜  ~/exo/cli git:(tgrondier/sc-118859/exo-cli-bucket-replication-support) go run . storage show sos://box-replication/Screenshot_20231127_112615.png                                                                                                                                                        25-02-20 14:40 
┼────────────────────┼───────────────────────────────────────────────────────────────────────────┼
│      STORAGE       │                                                                           │
┼────────────────────┼───────────────────────────────────────────────────────────────────────────┼
│ Path               │ Screenshot_20231127_112615.png                                            │
...
│ Replication Status │ REPLICA                                                                   │

┼────────────────────┼───────────────────────────────────────────────────────────────────────────┼
```