network: fix network retrieval by name (#175)
This change improves the Privnet Network retrieval by name, following a
bug report demonstrating that some CLI operations fail in presence of
multiple similarly prefixed Private Networks since the Exoscale API
doesn't support Network resource search by name.

Before the change:

```
$ exo privnet list
┼──────────────────────────────────────┼─────────┼──────────┼──────┼───────────┼
│                  ID                  │  NAME   │   ZONE   │ DHCP │ INSTANCES │
┼──────────────────────────────────────┼─────────┼──────────┼──────┼───────────┼
│ 9a67b55f-fe2a-4aab-b988-fcd3e654dbdd │ test100 │ ch-gva-2 │ n/a  │ 0         │
│ 5c80218f-9887-4f02-afc6-fd8d300b837e │ test10  │ ch-gva-2 │ n/a  │ 0         │
│ bcb9d7e3-a997-48ee-bc15-5f45c5a003a3 │ test1   │ ch-gva-2 │ n/a  │ 0         │
┼──────────────────────────────────────┼─────────┼──────────┼──────┼───────────┼

$ exo privnet associate test1 vm0
error: more than one element found: apikey=EXOxxxxxxxxxxxxxxxxxxxxxxxx, canusefordeploy=true, command=listNetworks, keyword=test1, type=Isolated
```

With the change implemented:

```
$ ./exo privnet associate test1 vm0
Network:     test1
Description:
Zone:        ch-gva-2
IP Range:    n/a
┼─────────────────┼────────────┼
│ VIRTUAL MACHINE │ IP ADDRESS │
┼─────────────────┼────────────┼
│ vm0             │ n/a        │
┼─────────────────┼────────────┼
```