Pass the zone when listing result of blockstorage operations (#633)
# Description
After doing mutations on blockstorage related entities, we do a list to
display the change. However this listing was done on the default zone
and not on the zone where the update occurred. And because public API
only return blockstorage results that live in the same zone, this was
causing issues

Before (default zone is ch-gva-2)
```
❯ exo compute block create test-create -z at-vie-1 --size 100
 ✔ Creating block storage volume "test-create"... 3s
error: "test-create" not found in ListBlockStorageVolumesResponse: resource not found
```
(The volume was successfully created bu failed to be displayed) 

After
```
❯ go run . compute block create test-create -z at-vie-1 --size 100                 
 ✔ Creating block storage volume "test-create"... 3s
┼─────────────────────────┼──────────────────────────────────────┼
│  BLOCK STORAGE VOLUME   │                                      │
┼─────────────────────────┼──────────────────────────────────────┼
│ Block Storage Snapshots │ n/a                                  │
│ Blocksize               │ 4096                                 │
│ Created AT              │ 2024-08-23 09:54:03 +0000 UTC        │
│ ID                      │ 641e351c-81ee-41fd-8273-52965ccbf3ed │
│ Instance                │ n/a                                  │
│ Name                    │ test-create                          │
│ Size                    │ 100 GiB                              │
│ Labels                  │ n/a                                  │
│ State                   │ detached                             │
┼─────────────────────────┼──────────────────────────────────────┼
```


## Checklist
(For exoscale contributors)

* [ ] Changelog updated (under *Unreleased* block)
* [ ] Testing

## Testing

<!--
Describe the tests you did
-->